version: '3.9'
services:
  trooper-ms-order:
    container_name: ms-order
    build: ./
    ports:
      - 3003:3003
    volumes:
      - ./:/app/ms-order
    environment:
      - PORT=3003
      - DB_HOST=mysql-ms-order
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=ms-order
      - DB_PORT=3306
      - JWT_SECRET=MTk4OGExOTZkMWYyOWZjZjlmOTcwMWVjZWRjMzc1MzZkOGM0MmFjMjQ0NjcyZjIzZDQwOGU4YTQ1YWQ3NTRjZA==
    depends_on:
      - mysql-ms-order

  mysql-ms-order:
    container_name: mysql-ms-order
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql-order-volume-docker:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  mysql-ms-order-test:
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret

volumes:
  mysql-order-volume-docker:

networks: 
  default:
    name: trooper-network
    external: true
